services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prismaAPI@2026
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data: