services:
  prismaapi:
    container_name: "PrismaAPI"
    image: "gurudohimalaia/prismaapi:latest"
    ports:
      - "9027:9027"
    environment:
      - TZ=GMT-3
      - SPRING_PROFILES_ACTIVE=prod

      - DATABASE_IP=${DATABASE_IP}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

      - REDIS_IP=redis
      - REDIS_PORT=6379

    volumes:
      - ./logs:/app/logs

    restart: always

  redis:
    container_name: "Redis"
    image: "redis:alpine3.23"

    ports:
      - "6379:6379"

    restart: always